package edu.ijse.layered.bo.custom.impl;

import edu.ijse.layered.bo.custom.MedicineBO;
import edu.ijse.layered.dao.DAOFactory;
import edu.ijse.layered.dao.custom.CategoryDAO;
import edu.ijse.layered.dao.custom.MedicineDAO;
import edu.ijse.layered.dao.custom.SupplierDAO;
import edu.ijse.layered.dto.MedicineDTO;
import edu.ijse.layered.entity.Category;
import edu.ijse.layered.entity.Medicine;
import edu.ijse.layered.entity.Supplier;
import java.util.ArrayList;
import java.util.List;

public class MedicineBOImpl implements MedicineBO {

    CategoryDAO categoryDAO = (CategoryDAO) DAOFactory.getInstance().getDAO(DAOFactory.DAOTypes.CATEGORY);
    MedicineDAO medicineDAO = (MedicineDAO) DAOFactory.getInstance().getDAO(DAOFactory.DAOTypes.MEDICINE);
    SupplierDAO supplierDAO = (SupplierDAO) DAOFactory.getInstance().getDAO(DAOFactory.DAOTypes.SUPPLIER);

    @Override
    public boolean save(MedicineDTO medicineDTO) throws Exception {

        Category category = categoryDAO.findById(medicineDTO.getCategoryId());
        Supplier supplier = supplierDAO.findById(medicineDTO.getSupplierId());

        Medicine medicine = new Medicine(
                0,                                                          // auto-generated by DB
                medicineDTO.getName(),
                category,
                supplier,                                                       // supplier — not in DTO; set null or extend DTO as needed
                medicineDTO.getUnitPrice(),
                medicineDTO.getQtyOnHand(),
                medicineDTO.getExpireDate() != null
                        ? medicineDTO.getExpireDate().toString()           // LocalDate → "yyyy-MM-dd" String
                        : null,
                null
        );

        return medicineDAO.save(medicine);
    }

    @Override
    public boolean update(MedicineDTO medicineDTO) throws Exception {

        Category category = categoryDAO.findById(medicineDTO.getCategoryId());
        Supplier supplier = supplierDAO.findById(medicineDTO.getSupplierId());

        Medicine medicine = new Medicine(
                medicineDTO.getMedicineId(),
                medicineDTO.getName(),
                category,
                supplier,                                                       // supplier — not in DTO
                medicineDTO.getUnitPrice(),
                medicineDTO.getQtyOnHand(),
                medicineDTO.getExpireDate() != null
                        ? medicineDTO.getExpireDate().toString()
                        : null,
                null
        );

        return medicineDAO.update(medicine);
    }

    @Override
    public boolean delete(Integer id) throws Exception {
        return medicineDAO.delete(id);
    }

    @Override
    public MedicineDTO findById(Integer id) throws Exception {

        Medicine medicine = medicineDAO.findById(id);

        if (medicine != null) {
            return new MedicineDTO(
                    medicine.getMedicineId(),
                    medicine.getName(),
                    medicine.getCategory() != null ? medicine.getCategory().getCategoryId() : 0,
                    medicine.getSupplier() != null ? medicine.getSupplier().getSupplierId() : 0,
                    medicine.getUnitPrice(),
                    medicine.getQtyOnHand(),
                    medicine.getExpireDate() != null
                            ? java.time.LocalDate.parse(medicine.getExpireDate())  // String → LocalDate
                            : null
            );
        }

        return null;
    }

    @Override
    public List<MedicineDTO> getAll() throws Exception {

        List<Medicine> medicines = medicineDAO.getAll();
        List<MedicineDTO> medicineDTOs = new ArrayList<>();

        for (Medicine medicine : medicines) {
            medicineDTOs.add(new MedicineDTO(
                    medicine.getMedicineId(),
                    medicine.getName(),
                    medicine.getCategory() != null ? medicine.getCategory().getCategoryId() : 0,
                    medicine.getSupplier() != null ? medicine.getSupplier().getSupplierId() : 0,
                    medicine.getUnitPrice(),
                    medicine.getQtyOnHand(),
                    medicine.getExpireDate() != null
                            ? java.time.LocalDate.parse(medicine.getExpireDate())
                            : null
            ));
        }

        return medicineDTOs;
    }
}